import requests

def get_bibtex(key):
    headers = {'Accept': 'application/x-bibtex'}
    if ":" in key:
        # Key is an inspires key of the form Author:year
        url = f"https://inspirehep.net/api/literature?q={key}"
    elif key.isdigit():
        # Key is a a unique Inspire identifier
        url = f"https://inspirehep.net/api/literature/{key}"
    else:
        raise ValueError(f"Key {key} not understood")
    response = requests.get(url, headers=headers)
    bibtext = response.text
    if len(bibtext) == 0:
        raise ValueError(f"Error: failed to find a bibkey for {key}")
    return bibtext


bibfile = "bibliography.bib"
keyfile = "bibliography.keys"
sedfile = "updatetexkeys.sed"
keyfile_valid = keyfile + ".valid"
keyfile_alias = keyfile + ".alias"
base_bibfile = "base_" + bibfile
baseline = f"%%% CONTENT TAKEN FROM {base_bibfile} %%%"
autogenline = "%%% CONTENT BELOW THIS LINE IS AUTOGENERATED %%%"


if __name__ == "__main__":

    import sys
    import tqdm
    try:
        from itertools import pairwise
    except ImportError:
        # itertools.pairwise added in version 3.10
        def pairwise(iterable):
            # pairwise('ABCDEFG') → AB BC CD DE EF FG
            iterator = iter(iterable)
            a = next(iterator, None)
            for b in iterator:
                yield a, b
                a = b


    program = sys.argv.pop(0)
    entries = dict()
    aliases = dict()
    newkeys = set()

    # Behavior of this program depends on the program name:
    #  - create_program builds bibliography from scratch from key file
    #  - update_program updates bibliography from key file or arguments

    create_program = "create_bibliography"
    update_program = "update_bibliography"

    if create_program in program:

        usage = f"usage: {program} [-h | --help]"

        if "-h" in sys.argv or "--help" in sys.argv:
            print(usage, file=sys.stderr)
            sys.exit()

        if sys.argv:
            print(f"error: unrecognized arguments {' '.join(sys.argv)}", file=sys.stderr)
            sys.exit(usage)

        # Create from scratch: don't read in existing bibliography or aliases

    elif update_program in program:

        usage = f"usage: {program} [-h | --help] [texkey ...]"

        if "-h" in sys.argv or "--help" in sys.argv:
            print(usage, file=sys.stderr)
            sys.exit()

        # New keys to add from arguments

        for key in sys.argv:
            newkeys.add(key)

        # Read in aliases

        try:
            with open(keyfile_alias, "r") as file:
                aliases = eval(file.read())
        except FileNotFoundError:
            pass

        assert isinstance(aliases, dict)

        # Load current bibliography.bib

        with open(bibfile, "r") as file:
            lines = [line.rstrip() for line in file]

        # Strip out lines before autogenline

        if autogenline in lines:
            lines = lines[lines.index(autogenline)+1:]

        # Partition lines into bibtex entries

        partitions = [idx for idx, line in enumerate(lines) if line.startswith("@")]
        partitions += [len(lines)]
        slices = [lines[i:j] for i, j in pairwise(partitions)]
        entries = dict()
        for entry in slices:
            texkey = entry[0].split('{')[1].split(',')[0]
            entries[texkey] = "\n".join(entry)

    else:

        # Program must be create_bibliography or update_bibliography
        exit(f"unrecognized program name: {program}")


    # Read in keys from keyfile; preserve comments

    keylines = dict()
    with open(keyfile, "r") as file:
        for line in file:
            line = line.rstrip()
            key = line.split("#")[0].rstrip()
            keylines[key] = line

    allkeys = set(keylines.keys())

    # Add any newkeys if updating

    allkeys |= newkeys

    # New keys that are not yet in bibliography nor in aliases

    newkeys = allkeys - aliases.keys() - entries.keys()

    if not newkeys:
        #print("nothing to be done", file=sys.stderr)
        #sys.exit()
        pass

    for key in tqdm.tqdm(newkeys):
        try:
            entry = get_bibtex(key)
        except ValueError:
            print(f"Unable to find a record for {key}: this will be ignored")
            continue
        texkey = entry.split('{')[1].split(',')[0]
        if texkey not in entries:
            entries[texkey] = entry
        if key != texkey:
            aliases[key] = texkey

    # If new keys were found, add them to allkeys

    allkeys |= entries.keys()

    # Write updated keyfile, keeping original line comments

    with open(keyfile, "w") as file:
        for key in sorted(allkeys):
            print(keylines[key] if key in keylines else key, file=file)

    # Write valid keyfile

    with open(keyfile_valid, "w") as file:
        print("\n".join(k for k in sorted(entries)), file=file)

    # Write outdated key aliases

    with open(keyfile_alias, "w") as file:
        print(repr(aliases), file=file)

    # Write sed command script to update keys

    with open(sedfile, "w") as file:
        print("\n".join(f"s/{k}/{v}/g" for k, v in sorted(aliases.items())), file=file)

    # Write updated bibliography

    with open(bibfile, "w") as file:
        try:
            with open(base_bibfile, "r") as f:
                print(baseline, end="\n\n", file=file)
                for line in f:
                    print(line, end="", file=file)
        except FileNotFoundError:
            pass
        print(autogenline, end="\n\n", file=file)
        print("\n".join(v for _, v in sorted(entries.items())), file=file)
