import pandas as pd


def numbers_to_words(text):
    lookup = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
    for nint, ntext in enumerate(lookup):
        text = text.replace(str(nint), ntext)
    return text


def print_macro(latex_key, command, status, filename):
    line = f'\\newcommand{{\\{latex_key}}}{{{{\\color{{{status}}}{{{command}}}}}}}'
    with open(filename, "a") as file:
        print(line, file=file)


def get_status_flag(reviewed):
    if pd.isna(reviewed):
        return "NOTAPPLICABLE"
    elif reviewed.lower() in ["n", "no"]:
        return "UNREVIEWED"
    elif reviewed.lower() in ["y", "yes"]:
        return "REVIEWED"
    else:
        raise ValueError("Value of reviewed {reviewed} is not understood")


def initialise_file(filename, extra=None):
    review_colors_preamble = "\n".join([
        ""
        "\\providecolor{UNREVIEWED}{rgb}{1,0,0}",
        "\\providecolor{REVIEWED}{rgb}{0,.5,.5}",
        "\\providecolor{NOTAPPLICABLE}{rgb}{0,0.5,0}",
        ""
    ])

    with open(filename, "w+") as file:
        print("%% THIS FILE IS AUTOGENERATED - DO NOT EDIT", file=file)
        print(review_colors_preamble, file=file)
        if extra:
            print(extra, file=file)


# Parse datetime
df = pd.read_csv("data/datetimes.csv", header=0, comment="#", skipinitialspace=True, parse_dates=["datetime_utc"])

if isinstance(df.datetime_utc.iloc[0], str):
    raise ValueError("Datatime conversion has failed: likely your data in datetimes.csv are not correctly formatted")
datetime_macros_file = "macros/datetime_macros.tex"

initialise_file(datetime_macros_file)
for _, row in df.iterrows():
    if pd.isna(row.latex_key):
        latex_key = numbers_to_words(row.key)
        latex_key = "".join(x.capitalize() for x in latex_key.split("_"))
        latex_key = latex_key.replace("-", "").replace(".", "p")
    else:
        latex_key = row.latex_key

    status = get_status_flag(row.reviewed)
    apj_format_date = row.datetime_utc.strftime("%Y~%B~%d")
    apj_format_time = row.datetime_utc.strftime("%H:%M:%S")
    print_macro(latex_key + "Date", apj_format_date, status, datetime_macros_file)
    print_macro(latex_key + "Time", apj_format_time, status, datetime_macros_file)


# Parse quantities
quantities_macros_file = "macros/quantities_macros.tex"
quantities_extras = """
\\DeclareSIUnit\\parsec{pc}
\\DeclareSIUnit\\Mpc{\\mega\\parsec}
\\DeclareSIUnit\\yr{yr}
\\DeclareSIUnit\\GpcCubedYear{\\giga\\parsec\\cubed\\yr}
"""
initialise_file(quantities_macros_file, quantities_extras)

qtyfiles = [
    "data/range_quantities.csv",
    "data/dutycycle_quantities.csv",
    "data/vt_quantities.csv",
    "data/ifo_quantities.csv",
    "data/other_quantities.csv",
]
for qtyfile in qtyfiles:
    print('processing file', qtyfile)
    df = pd.read_csv(qtyfile, header=0, comment="#", skipinitialspace=True, dtype=str)
    for _, row in df.iterrows():
        if pd.isna(row.latex_key):
            latex_key = numbers_to_words(row.key)
            latex_key = "".join(x.capitalize() for x in latex_key.split("_"))
            latex_key = latex_key.replace("-", "").replace(".", "p")
        else:
            latex_key = row.latex_key

        value = row.value
        unit = row.unit
        status = get_status_flag(row.reviewed)
        if pd.isna(unit):
            command = f"\\num{{{value}}}"
        else:
            escape_unit = ".\\".join(unit.split())
            command = f"\\qty{{{value}}}{{\\{escape_unit}}}"
        print_macro(latex_key, command, status, quantities_macros_file)
